<?php

namespace AppBundle\Repository;

/**
 * homelinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class homelinksRepository extends \Doctrine\ORM\EntityRepository
{
}
