index_page :
  path : /
  defaults: { _controller: AppBundle:Default:home }

home_page :
  path:     /home
  defaults: { _controller: AppBundle:Default:home }

login : 
  path : /login
  defaults: { _controller: FOSUserBundle:Security:login }

register :
  path : /register
  defaults : { _controller: FOSUserBundle:Registration:register }